server:
  port: 9000
spring:
  application:
    name: "harvester"
  cloud:
    config:
      uri: "http://localhost:9000"
      fail-fast: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9010/eureka/
